### ISSUE TITLE
Infografía actividad 1

### ISSUE THREAD

**Issue by AricelCastro** [SistemasTecTlaxiaco/actividad-1-infografia-AricelCastro#1]
![IMG-20240827-WA0004](https://github.com/user-attachments/assets/115ccaea-16f0-4d20-9705-7d6594995456)

**Comment by williamgl3** [comment]
18 
buena informacion, falto el uso de imagenes

**Comment by williamgl3** [comment]
18
buena informacion falto el uso de imagenes (segun la rubrica)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
